#ifndef __DBN_GRAPHVIZ_WIDGET_H__
#define __DBN_GRAPHVIZ_WIDGET_H__

#include "wx/txtstrm.h"
#include "wx/mstream.h"
#include "wx/sstream.h"
#include <wx/wx.h>
#include <wx/rawbmp.h>
#include "wx/process.h"
#include "wx/image.h"
#include <thinkerbell/deep_belief_network.h>

#define ID_VERTEX_MENU_DELETE        69000
#define ID_VERTEX_MENU_ZERO_BIASES   69001
#define ID_EDGE_MENU_DELETE          69002
#define ID_EDGE_MENU_RANDOMIZE       69003

class wxDbnGraphvizControl : public wxScrolled<wxWindow>
{
  
public:
  wxDbnGraphvizControl(wxFrame* parent);
  
  void paintEvent(wxPaintEvent & evt);
  void paintNow();
  void update_graphviz( thinkerbell::DBN &dbn );
  
  void render(wxDC& dc);
  
  void mouseDown(wxMouseEvent& event);
  void mouseReleased(wxMouseEvent& event);
  void OnContext(wxContextMenuEvent& event);
  
  DECLARE_EVENT_TABLE()
private:
  void HandleOnScroll(wxScrollWinEvent& event);
  wxImage * m_graph_image;
  wxSize m_graph_image_size; // we'll use the size generated by 'dot'

  wxString m_graph_image_map_string;
  std::multimap< thinkerbell::Vertex, wxRegion > m_graph_image_map_vertices;
  std::multimap< thinkerbell::Edge, wxRegion > m_graph_image_map_edges;
  void parse_image_map(thinkerbell::DBN &dbn, const wxString& image_map_string);
  wxRegion parse_rectangle_string( std::string tl, std::string br );
};

class wxVertexMenu : public wxMenu 
{
public:
  wxVertexMenu(thinkerbell::Vertex v, wxDbnGraphvizControl * parent_);

  void OnDelete( wxCommandEvent& e );
  void OnZeroBiases( wxCommandEvent& e );
  DECLARE_EVENT_TABLE()
private:
  wxDbnGraphvizControl * parent;
  thinkerbell::Vertex vertex;
};
 
class wxEdgeMenu : public wxMenu 
{
public:
  wxEdgeMenu(thinkerbell::Edge e, wxDbnGraphvizControl * parent_);

  void OnDelete( wxCommandEvent& e );
  void OnRandomize( wxCommandEvent& e );
  DECLARE_EVENT_TABLE()
private:
  wxDbnGraphvizControl * parent;
  thinkerbell::Edge edge;
};
 
#endif
