#ifndef __train_frame__
#define __train_frame__


/**
@file
Subclass of TrainGui, which is generated by wxFormBuilder.
*/

#include <wx/filename.h>
#include <wx/filedlg.h>
#include <vector>
#include "mnist_handwritten_digits/train/train_gui.h"
#include "training_example_widget.h"

class TrainApp;

/** Implementing TrainGui */
class TrainFrame : public TrainGui
{
public:
	/** Constructor */
	TrainFrame( wxWindow* parent, TrainApp* app );
protected:
  // Event handlers
  // Menus
  // File menu
  void OnFileNew( wxCommandEvent& event );
  void OnFileOpen( wxCommandEvent& event );
  void OnFileSave( wxCommandEvent& event );
  void OnFileSaveAs( wxCommandEvent& event );
  void OnFileQuit( wxCommandEvent& event );

  // Train menu
  void OnTrainGreedy( wxCommandEvent& event );

  // Visualize menu
  void OnViewReconstructions( wxCommandEvent& event );

  // DBN controls
  void OnSelectVertex( wxCommandEvent& event );
  void OnSelectEdge( wxCommandEvent& event );

  // Vertex controls
  void OnNeuronsApplyChanges( wxCommandEvent& event );

  // Edge controls
  void OnEdgeRandomize( wxCommandEvent& event );
private:
  TrainApp * app;

  thinkerbell::Vertex * SelectedVertex();
  thinkerbell::Edge * SelectedEdge();

  void append_vertex(thinkerbell::Vertex v);
  void append_edge( thinkerbell::Edge e );

  std::list<thinkerbell::Vertex> vertices;
  std::list<thinkerbell::Edge> edges;

  void update_dbn_controls();
  void update_vertex_controls();
  void update_edge_controls();

};


class GreedyLearningFrame : public GreedyLearningGui
{
public:
	GreedyLearningFrame( wxWindow* parent, TrainApp* app );
protected:
  // Event handlers
  void OnTrainingStart( wxCommandEvent& event );
  void OnTrainingStop( wxCommandEvent& event );
private:
  TrainApp * app;
  GreedyLearningFrame* greedy_learning_frame;
  void trainefy();
};

class VisualizeReconstructionsFrame : public VisualizeReconstructionsGui
{
public:
  VisualizeReconstructionsFrame( wxWindow* parent, TrainApp* app );
  ~VisualizeReconstructionsFrame();
protected:
  // Event handlers
  void OnChangeExample( wxSpinEvent& event );
  void OnTimerEvent(wxTimerEvent &event);
private:
  TrainApp * app;
  wxTimer m_timer;
};

#endif // __train_frame__
