#ifndef __train_frame__
#define __train_frame__


/**
@file
Subclass of TrainGui, which is generated by wxFormBuilder.
*/

#include <wx/filename.h>
#include <wx/filedlg.h>
#include <vector>
#include "mnist_handwritten_digits/train/train_gui.h"
#include "training_example_widget.h"

using thinkerbell::Vertex;
using thinkerbell::Edge;

class TrainApp;

/** Implementing TrainGui */
class TrainFrame : public TrainGui
{
public:
	/** Constructor */
	TrainFrame( wxWindow* parent, TrainApp* app );
  // Vertex context menu
  void OnDeleteVertex(Vertex v);
  void OnZeroBiases( Vertex v );
  // Edge context menu
  void OnDeleteEdge(Edge e);
  void OnEdgeRandomize(Edge e);

  // temporary debug stuff
  void stats_vertex(Vertex v);
  void stats_edge( Edge e );
  void toggle_vertex( Vertex v );
protected:
  // Event handlers
  // Menus
  // File menu
  void OnFileNew( wxCommandEvent& event );
  void OnFileOpen( wxCommandEvent& event );
  void OnFileSave( wxCommandEvent& event );
  void OnFileSaveAs( wxCommandEvent& event );
  void OnFileQuit( wxCommandEvent& event );

  // Train menu
  void OnTrainGreedy( wxCommandEvent& event );

  // Visualize menu
  void OnViewReconstructions( wxCommandEvent& event );

  // DBN controls
  void OnSelectVertex( wxCommandEvent& event );
  void OnSelectEdge( wxCommandEvent& event );

  // Vertex controls
  void OnNeuronsApplyChanges( wxCommandEvent& event );
private:
  TrainApp * app;

  Vertex * SelectedVertex();
  Edge * SelectedEdge();

  void append_vertex(Vertex v);
  void append_edge( Edge e );

  std::list<Vertex> vertices;
  std::list<Edge> edges;

  void update_dbn_controls();
  void update_vertex_controls();
  void update_edge_controls();

  wxString current_dbn_file;

};


class GreedyLearningFrame : public GreedyLearningGui
{
public:
	GreedyLearningFrame( wxWindow* parent, TrainApp* app );
protected:
  // Event handlers
  void OnTrainingStart( wxCommandEvent& event );
  void OnTrainingStop( wxCommandEvent& event );
  void OnChangeLearningRate( wxCommandEvent& event );
private:
  TrainApp * app;
  GreedyLearningFrame* greedy_learning_frame;
  void trainefy();
};

class VisualizeReconstructionsFrame : public VisualizeReconstructionsGui
{
public:
  VisualizeReconstructionsFrame( wxWindow* parent, TrainApp* app );
  ~VisualizeReconstructionsFrame();
protected:
  // Event handlers
  void OnChangeExample( wxSpinEvent& event );
  void OnTimerEvent(wxTimerEvent &event);
  void OnTemperatureChanged(wxScrollEvent &event);
  void OnNumAgsIterationsChanged(wxScrollEvent &event);
private:
  TrainApp * app;
  wxTimer m_timer;
  float temperature;
  int num_ags_iterations;
};

#endif // __train_frame__
